export const PREDEFINED_CURRENCIES = [
    { symbol: '$', name: 'US Dollar' },
    { symbol: '€', name: 'Euro' },
    { symbol: '£', name: 'British Pound' },
    { symbol: '¥', name: 'Japanese Yen' },
    { symbol: '₹', name: 'Indian Rupee' },
    { symbol: '₽', name: 'Russian Ruble' },
    { symbol: '₩', name: 'South Korean Won' },
    { symbol: '₦', name: 'Nigerian Naira' },
    { symbol: '₨', name: 'Pakistani Rupee' },
     { symbol: '₫', name: 'Vietnamese Dong' },
    { symbol: '₡', name: 'Costa Rican Colón' },
    { symbol: '₹', name: 'Indian Rupee' },
    { symbol: '﷼', name: 'Saudi Riyal' },
    { symbol: '₱', name: 'Philippine Peso' },
    { symbol: '₴', name: 'Ukrainian Hryvnia' },
    { symbol: '₸', name: 'Kazakhstani Tenge' },
    { symbol: '₼', name: 'Azerbaijani Manat' },
    { symbol: '₾', name: 'Georgian Lari' },
    { symbol: 'C$', name: 'Canadian Dollar' },
    { symbol: 'A$', name: 'Australian Dollar' },
    { symbol: 'NZ$', name: 'New Zealand Dollar' },
    { symbol: 'S$', name: 'Singapore Dollar' },
    { symbol: 'HK$', name: 'Hong Kong Dollar' },
    { symbol: 'CHF', name: 'Swiss Franc' },
    { symbol: 'kr', name: 'Swedish Krona' },
    { symbol: 'kr', name: 'Norwegian Krone' },
    { symbol: 'kr', name: 'Danish Krone' },
    { symbol: 'zł', name: 'Polish Złoty' },
    { symbol: 'Kč', name: 'Czech Koruna' },
    { symbol: 'Ft', name: 'Hungarian Forint' },
    { symbol: 'lei', name: 'Romanian Leu' },
    { symbol: 'лв', name: 'Bulgarian Lev' },
    { symbol: 'kn', name: 'Croatian Kuna' },
    { symbol: 'din', name: 'Serbian Dinar' },
    { symbol: 'TL', name: 'Turkish Lira' },
    { symbol: 'R', name: 'South African Rand' },
    { symbol: 'R$', name: 'Brazilian Real' },
    { symbol: '$', name: 'Mexican Peso' },
    { symbol: '$', name: 'Argentine Peso' },
    { symbol: '$', name: 'Chilean Peso' },
    { symbol: '$', name: 'Colombian Peso' },
    { symbol: 'S/', name: 'Peruvian Sol' },
    { symbol: 'Bs', name: 'Venezuelan Bolívar' },
    { symbol: '$U', name: 'Uruguayan Peso' },
    { symbol: 'Gs', name: 'Paraguayan Guaraní' },
    { symbol: '$b', name: 'Bolivian Boliviano' },
    { symbol: '¢', name: 'Guatemalan Quetzal' },
    { symbol: 'L', name: 'Honduran Lempira' },
    { symbol: 'C$', name: 'Nicaraguan Córdoba' },
    { symbol: '₡', name: 'Costa Rican Colón' },
    { symbol: 'B/.', name: 'Panamanian Balboa' },
    { symbol: 'RD$', name: 'Dominican Peso' },
    { symbol: 'J$', name: 'Jamaican Dollar' },
    { symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
    { symbol: 'EC$', name: 'East Caribbean Dollar' },
    { symbol: 'B$', name: 'Bahamian Dollar' },
    { symbol: 'BD$', name: 'Bermudian Dollar' },
    { symbol: 'CI$', name: 'Cayman Islands Dollar' },
    { symbol: '¥', name: 'Chinese Yuan' },
    { symbol: '₩', name: 'South Korean Won' },
    { symbol: '₹', name: 'Indonesian Rupiah' },
    { symbol: 'RM', name: 'Malaysian Ringgit' },
    { symbol: '฿', name: 'Thai Baht' },
    { symbol: '₫', name: 'Vietnamese Dong' },
    { symbol: '₱', name: 'Philippine Peso' },
    { symbol: 'K', name: 'Myanmar Kyat' },
    { symbol: '₭', name: 'Lao Kip' },
    { symbol: '៛', name: 'Cambodian Riel' },
    { symbol: '$', name: 'Brunei Dollar' },
    { symbol: 'FJ$', name: 'Fijian Dollar' },
    { symbol: 'T$', name: 'Tongan Paʻanga' },
    { symbol: 'WS$', name: 'Samoan Tālā' },
    { symbol: 'VT', name: 'Vanuatu Vatu' },
    { symbol: 'SBD', name: 'Solomon Islands Dollar' },
    { symbol: 'PGK', name: 'Papua New Guinea Kina' },
    { symbol: 'AED', name: 'UAE Dirham' },
    { symbol: 'QR', name: 'Qatari Riyal' },
    { symbol: 'KD', name: 'Kuwaiti Dinar' },
    { symbol: 'BD', name: 'Bahraini Dinar' },
    { symbol: 'OMR', name: 'Omani Rial' },
    { symbol: 'JD', name: 'Jordanian Dinar' },
    { symbol: 'LBP', name: 'Lebanese Pound' },
    { symbol: 'SYP', name: 'Syrian Pound' },
    { symbol: 'IQD', name: 'Iraqi Dinar' },
    { symbol: 'IRR', name: 'Iranian Rial' },
    { symbol: '₼', name: 'Azerbaijani Manat' },
    { symbol: '₾', name: 'Georgian Lari' },
    { symbol: '₸', name: 'Kazakhstani Tenge' },
    { symbol: 'сом', name: 'Kyrgyzstani Som' },
    { symbol: 'сом', name: 'Uzbekistani Som' },
    { symbol: 'TMT', name: 'Turkmenistani Manat' },
    { symbol: 'TJS', name: 'Tajikistani Somoni' },
    { symbol: '₹', name: 'Afghan Afghani' },
    { symbol: '₹', name: 'Pakistani Rupee' },
    { symbol: '₹', name: 'Sri Lankan Rupee' },
    { symbol: '₹', name: 'Nepalese Rupee' },
    { symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
    { symbol: '₹', name: 'Maldivian Rufiyaa' },
    { symbol: 'Tk', name: 'Bangladeshi Taka' },
    { symbol: 'E£', name: 'Egyptian Pound' },
    { symbol: 'LD', name: 'Libyan Dinar' },
    { symbol: 'DH', name: 'Moroccan Dirham' },
    { symbol: 'DA', name: 'Algerian Dinar' },
    { symbol: 'DT', name: 'Tunisian Dinar' },
    { symbol: 'Br', name: 'Ethiopian Birr' },
    { symbol: 'Nkf', name: 'Eritrean Nakfa' },
    { symbol: 'SDG', name: 'Sudanese Pound' },
    { symbol: 'SSP', name: 'South Sudanese Pound' },
    { symbol: 'USh', name: 'Ugandan Shilling' },
    { symbol: 'KSh', name: 'Kenyan Shilling' },
    { symbol: 'TSh', name: 'Tanzanian Shilling' },
    { symbol: 'RWF', name: 'Rwandan Franc' },
    { symbol: 'FBu', name: 'Burundian Franc' },
    { symbol: 'FC', name: 'Congolese Franc' },
    { symbol: 'FCFA', name: 'Central African CFA Franc' },
    { symbol: 'FCFA', name: 'West African CFA Franc' },
    { symbol: 'D', name: 'Gambian Dalasi' },
    { symbol: 'Le', name: 'Sierra Leonean Leone' },
    { symbol: 'L$', name: 'Liberian Dollar' },
    { symbol: '₵', name: 'Ghanaian Cedi' },
    { symbol: '₦', name: 'Nigerian Naira' },
    { symbol: 'FCFA', name: 'Beninese Franc' },
    { symbol: 'FCFA', name: 'Burkina Faso Franc' },
    { symbol: 'FCFA', name: 'Ivorian Franc' },
    { symbol: 'MRU', name: 'Mauritanian Ouguiya' },
    { symbol: 'MT', name: 'Mozambican Metical' },
    { symbol: 'P', name: 'Botswana Pula' },
    { symbol: 'L', name: 'Lesotho Loti' },
    { symbol: 'E', name: 'Swazi Lilangeni' },
    { symbol: '$', name: 'Namibian Dollar' },
    { symbol: 'Z$', name: 'Zimbabwean Dollar' }
];